// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVi4DJa03qLYPxnChebdbkg4-p-sPdOW8',
    appId: '1:905452996013:web:c8ab495e82208033c68d24',
    messagingSenderId: '905452996013',
    projectId: 'telehealth-b9a5a',
    authDomain: 'telehealth-b9a5a.firebaseapp.com',
    storageBucket: 'telehealth-b9a5a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZ3DYCdV3ya8Gn7rbCHBYvGWRuODJhbns',
    appId: '1:905452996013:android:a053fba9c3054272c68d24',
    messagingSenderId: '905452996013',
    projectId: 'telehealth-b9a5a',
    storageBucket: 'telehealth-b9a5a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgkU4wHRhxq9WRmraWmPa7b3iWResuqQY',
    appId: '1:905452996013:ios:ebb80b59d97b057fc68d24',
    messagingSenderId: '905452996013',
    projectId: 'telehealth-b9a5a',
    storageBucket: 'telehealth-b9a5a.appspot.com',
    iosBundleId: 'com.example.telehelth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCgkU4wHRhxq9WRmraWmPa7b3iWResuqQY',
    appId: '1:905452996013:ios:ebb80b59d97b057fc68d24',
    messagingSenderId: '905452996013',
    projectId: 'telehealth-b9a5a',
    storageBucket: 'telehealth-b9a5a.appspot.com',
    iosBundleId: 'com.example.telehelth',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAVi4DJa03qLYPxnChebdbkg4-p-sPdOW8',
    appId: '1:905452996013:web:6563a622351fced5c68d24',
    messagingSenderId: '905452996013',
    projectId: 'telehealth-b9a5a',
    authDomain: 'telehealth-b9a5a.firebaseapp.com',
    storageBucket: 'telehealth-b9a5a.appspot.com',
  );
}
